// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJDn2R97m_90l1GlAl5sZ_Z4pOrEZIWY',
    appId: '1:862406504590:web:1c95e1496eed9bd84b59df',
    messagingSenderId: '862406504590',
    projectId: 'kutagjej',
    authDomain: 'kutagjej.firebaseapp.com',
    storageBucket: 'kutagjej.appspot.com',
    measurementId: 'G-LPEWP1X0K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJGjaAlslIN3NFxhx4lmJvG4tgYBiOyk8',
    appId: '1:862406504590:android:03cd0d9b207498274b59df',
    messagingSenderId: '862406504590',
    projectId: 'kutagjej',
    storageBucket: 'kutagjej.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCos34keMBbaClb_tOPjKQ6iFU8VPBVdxk',
    appId: '1:862406504590:ios:0a359812e181c5964b59df',
    messagingSenderId: '862406504590',
    projectId: 'kutagjej',
    storageBucket: 'kutagjej.appspot.com',
    iosBundleId: 'com.bonnle.kutagjej',
  );
}
